Use speedy XOR from pion/transport
pion/srtp pull request #208
Opened 2022-06-02 10:43 UTC by jech

Now that we have a speedy version of xorBytes in pion/transport,
we might as well use it.  Benchmarks indicate an improvement
of 10% to 20% in CTR encryption speed for large blocks, depending
on the architecture.

2022-06-02 22:15 UTC, adriancable requested changes

2022-06-02 22:15 UTC, adriancable commented on crypto.go
> -
Also @jech the length check is not needed, since this is already done in xor.XorBytes.

2022-06-03 12:20 UTC, jech commented
The semantics of xorBytes and your version is not quite the same — your version panics if the destination is too short, while the version here truncates the output.  The simplest solution was to write a version of xorBytes that uses your code while exactly duplicating the semantics of the old version.

I can have a look to see if we can do without going through an intermediate function, but it will require carefully examining all call sites.

2022-06-14 23:29 UTC, adriancable commented
@jech - I'm probably OK with the double-call. Can you post some benchmarks here? It's always good to have benchmarks in the PR.

2022-06-17 20:12 UTC, jech commented
@adriancable you were right, the indirection was not needed.  Superseded by #211.

2022-06-17 20:12 UTC, closed without merging